### ISSUE TITLE
Combine layers not working

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#109]
Combine layers isn't working. The screenshot was taken after:
- running default ABM scenario
- running default wind
- clicking on "Combine Layers" -> the loading screen works and the button indicates loading, but no results appear 

![grafik](https://user-images.githubusercontent.com/45463490/150379883-1f5ede2d-ede1-48fc-8b24-9e74197006a4.png)

**Comment by andredaa** [comment]
fixed with https://github.com/digitalcityscience/functionalscope-frontend/commit/ad128e1aa2fd81049d053629a517c19eb2aa312a
