### ISSUE TITLE
Noise results come back identical for defaults

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#115]
The example scenario buttons for Noise return identical mapping results. 
I first clicked down the list of examples, and noticed that they were all the same. Then I tested by choosing the attributes 0% traffic and 30kmh and the mapping results also came back the same as the bottons. 

![grafik](https://user-images.githubusercontent.com/45463490/153029920-890098f3-3428-45e7-a4d3-85e0e4abda78.png)

**Comment by andredaa** [comment]
found the bug https://github.com/digitalcityscience/functionalscope-noise/blob/8aed2ef8ede9e3fe32b2002ec0f6057e5affa880/noise_analysis/sql_query_builder.py#L82  - check for keys in roads["properties"] , also for some reason the boolean value is a string "true", "false"

**Comment by andredaa** [comment]
fixed with https://github.com/digitalcityscience/functionalscope-frontend/commit/45d14eb867534df0f1937cea4441e12fe4972688
