### ISSUE TITLE
Sun results missing

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#116]
Sun exposure results are missing. "Run simulation" does not return a map.

**Comment by andredaa** [comment]
https://github.com/digitalcityscience/functionalscope-frontend/blob/5f59eef5b4c3aac7402139cdcb99323e8f72dcc6/src/store/scenario/actions.ts#L36 quick fix, before we use the sun api anyway: results.results to access the geojson.

**Comment by andredaa** [comment]
fixed. https://github.com/digitalcityscience/functionalscope-frontend/commit/d7db7096c9d968756d1d336ce863eadbaaf9c259
