### ISSUE TITLE
Pedestrian Flow subarea selection polygons need to be updated

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#117]
The polygons used for calculating the ABM metrics are outdated. 
![grafik](https://user-images.githubusercontent.com/45463490/153031921-eac229ec-7f99-4411-8d4a-febe104afd4c.png)

**Comment by JLSievert** [comment]
@andredaa can you send me a link to the existing file? When I can make a new version.

**Comment by JLSievert** [comment]
@andredaa it also looks like the spaces file underneath is also outdated. Do we have a new version of that? Or did it not get converted?

**Comment by andredaa** [comment]
spaces fixed
