### ISSUE TITLE
Update name "Abm" to "Pedestrians" in Combine Layers tab

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#132]
"Abm" is still used in the Combine Layers tab. Update this to say "Pedestrians."

![grafik](https://user-images.githubusercontent.com/45463490/159163428-894f37a9-6b6a-4284-9da8-e6af013554e9.png)

**Comment by andredaa** [comment]
ABM result processing for combine layers not working for abm.
- if result was not loaded through abm component, but directly through combine layers
- other cases?

**Comment by andredaa** [comment]
fixed 
ac70fa423c9d2bb41cfa9479a3f476dd5b0ff4de
2fcd61ea1c8f27c15d32accc418546543e825ad5
