### ISSUE TITLE
Missing AIT/CIL/InFraRed Logos

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#134]
The AIT, CIL, and InFraRed Logos are missing on the lower right corner of the map. These should be shown for both the wind and sun modules. 

![grafik](https://user-images.githubusercontent.com/45463490/159300989-4a57de9d-403a-4d25-8a18-cafee6ab4c0a.png)

**Comment by andredaa** [comment]
fixed 0059cf4e9a527017704c39d61f0a0a1faf0e3901
