### ISSUE TITLE
Formatting updates for building info boxes

### ISSUE THREAD

**Issue by JLSievert** [digitalcityscience/functionalscope-frontend#91]
Add: 
- [ ] new line in whole building information (at the top), after "buidling height": "Gross Floor Area". This should show the gross floor area of the whole building. For now, this can be calculated as the sum of the the Gross Floor Area for "Upper Floors" and "Ground Floor". In future this could be a separate value that comes from the BIM export.

Formatting:
- [ ] Use title case throughout (e.g. building GXX -> Building GXX; building height -> Building Height)

Rename: 
- [x] "total floor area upperfloors" (Upper Floors) -> "Gross Floor Area"
- [x] "floor area" (Groundfloor) -> "Gross Floor Area"

Delete: 
- [x] "floor area" in upper floors
- [x] OD + trips slider

![grafik](https://user-images.githubusercontent.com/45463490/144072468-1152e9c9-a10d-4a8c-a739-d7238189c789.png)

**Comment by andredaa** [comment]
ah yeah. I guess this is urgent?

**Comment by JLSievert** [comment]
I wouldn't call it urgent, since it doesn't affect the main functions (simulations). More like a smaller thing that should be improved and clarification of what can be removed.

**Comment by andredaa** [comment]
done. we will need to refactor how we get building information :)) i make a new issue.
